AWSTemplateFormatVersion: 2010-09-09
Description: ---
# Metadata: 

# Parameters: 

# Mappings: 

# Conditions: 

Resources: 
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: SSH
      GroupDescription: SSH Security Group
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

# Outputs: