---
- hosts: webservers
  become: yes
  gather_facts: no
  tasks:
    - name: Set default boot target to multiuser
      systemd:
        name: multi-user.target
        state: started
        enabled: true
